import type { Metadata } from "next";

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <h1 className="">Mam Les Cro Mignon&apos;s</h1>
      <div className="flex flex-row items-center justify-center">
      </div>
    </div>
  );
}

export const metadata: Metadata = {
  title: "Notre équipe | Mam Les Cro Mignon's",
  description: "Generated by zogeek",
};
