import type { Metadata } from "next";

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-start h-screen">
      <div className="flex items-center justify-center h-5 mt-4">
        <h1 className="text-3xl font-bold">Mam Les Cro Mignon&apos;s</h1>
      </div>
      <div className="flex items-center justify-center h-5 mt-4">
        <h1 className="text-xl">Présentaition</h1>
      </div>
    </div>
  );
}

export const metadata: Metadata = {
  title: "Mam Les Cro Mignon's",
  description: "Generated by zogeek",
};
